[build]  
command = "npm run build"  
publish = "dist"  
functions = "netlify/functions"
  
[build.environment]  
GO_VERSION = "1.19"
NODE_VERSION = "23.5.0"

[dev]
framework = "#custom"
command = "npm run dev"
targetPort = 5173
port = 8888
publish = "dist"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

